"""Generate local human-review annotation packets for benchmark pairs.

    python scripts/create_real_filing_annotation_packets.py
    python scripts/create_real_filing_annotation_packets.py --pair-id X
    python scripts/create_real_filing_annotation_packets.py --validate FILE

A packet is review material for a person, NOT gold output. It shows the
extracted risk-factor units on both sides, what the detector proposed, where
its evidence points, and a pre-filled label form — all explicitly marked as
machine proposals.

The one thing this command cannot do
------------------------------------
It cannot produce a verified label. Every generated annotation file is written
with ``annotation_status='machine_proposed'`` and ``annotator_id=null``, and
``real_filing_benchmark.machine_proposed_annotation`` refuses to build anything
else. A human moves a file to ``human_verified`` by editing it, naming
themselves, and stamping a verification time. That edit is the entire
human-verification boundary, and no tool in this repository performs it.

There is deliberately no authentication for benchmark annotators: inventing an
identity system for a local research artifact would imply an assurance that
does not exist. ``annotator_id`` is self-asserted local metadata and is
labelled as such wherever it appears.

Exit codes: 0 success, 1 a packet or validation failure, 2 invalid arguments.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import comparison_detector  # noqa: E402
import real_filing_benchmark as rfb  # noqa: E402
from scripts import build_real_filing_benchmark as builder  # noqa: E402

PACKET_GENERATOR = "real_filing_annotation_packets.v1"

MACHINE_PROPOSAL_BANNER = (
    "MACHINE-PROPOSED — NOT GROUND TRUTH. Every label below was generated by "
    "the deterministic detector, not by a person. Nothing here counts toward "
    "any accuracy metric until a human reviewer edits the annotation file, "
    "sets annotation_status to 'human_verified', and supplies their own "
    "annotator_id and verification_timestamp."
)


def _units_for_alignment(record: dict[str, Any], side: str):
    """Rebuild detector unit objects from a build record for alignment.

    ``comparison_detector.align_units`` reads only ``unit_key`` and
    ``content_hash``, so the alignment a packet shows is produced by the real
    alignment function rather than a second implementation that could drift
    from it.
    """
    return [
        comparison_detector.RiskFactorUnit(
            unit_key=unit["unit_key"],
            heading=unit["heading"],
            filing_id=record[side]["filing_id"] or "",
            text="",
            content_hash=unit["content_hash"],
            chunks=[],
        )
        for unit in record[side]["units"]
    ]


def _unit_index(record: dict[str, Any], side: str) -> dict[str, dict[str, Any]]:
    """unit_key -> first unit on that side (ambiguous keys stay ambiguous)."""
    index: dict[str, dict[str, Any]] = {}
    for unit in record[side]["units"]:
        index.setdefault(unit["unit_key"], unit)
    return index


def _evidence_pointers(
    result: dict[str, Any] | None, unit_keys: set[str]
) -> dict[str, dict[str, list[str]]]:
    """change unit_key -> {side: [chunk_id]} recovered from detector output.

    The unit key is recovered by recomputing the detector's deterministic
    ``change_id``, the same technique the synthetic regression evaluator uses,
    so a packet never has to guess which change belongs to which unit.
    """
    pointers: dict[str, dict[str, list[str]]] = {}
    if not result:
        return pointers
    for change in result.get("changes", []):
        key = _unit_key_of(change["change_id"], unit_keys)
        if key is None:
            continue
        pointers.setdefault(key, {"previous": [], "current": []})
        for side in ("previous", "current"):
            pointers[key][side].extend(
                reference["chunk_id"] for reference in change[f"{side}_evidence"]
            )
    return pointers


def _unit_key_of(change_id: str, candidate_keys: set[str]) -> str | None:
    for key in sorted(candidate_keys):
        for change_type in ("added", "removed", "modified", "undetermined"):
            if change_id == comparison_detector._change_id(change_type, key):  # noqa: SLF001
                return key
    return None


def _proposed_changes(result: dict[str, Any] | None, unit_keys: set[str]):
    """[(unit_key, change_type, undetermined_reason)] from detector output."""
    proposed = []
    if not result:
        return proposed
    for change in result.get("changes", []):
        key = _unit_key_of(change["change_id"], unit_keys)
        proposed.append(
            (
                key,
                change["change_type"],
                change.get("undetermined_reason"),
                change["change_id"],
            )
        )
    return proposed


def build_packet(
    pair_id: str, layout: rfb.CorpusLayout, manifest: dict[str, Any]
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Return (packet, machine_proposed_annotation) for one built pair."""
    record = builder.load_build_record(pair_id, layout)
    if not rfb.build_is_evaluable(record):
        # A pair whose Item 1A did not extract has no section hash and no risk
        # units, so there is nothing for a human to review and no annotation
        # that could ever become gold. Refusing here reports the real cause;
        # letting it fall through produces the same zero packets but blames a
        # downstream hash-format rule, which reads like a schema bug rather
        # than the extraction outcome it actually is.
        raise rfb.BenchmarkError(
            "pair_not_annotatable",
            f"{pair_id}: Item 1A did not extract for both sides "
            f"(previous={record['previous']['extraction_outcome']}, "
            f"current={record['current']['extraction_outcome']}), so this pair "
            "has no reviewable risk units. It stays in the corpus and is "
            "reported as blocked; it is never replaced.",
        )
    result = builder.load_detection_result(pair_id, layout)

    previous_units = _units_for_alignment(record, "previous")
    current_units = _units_for_alignment(record, "current")
    pairs, unmatched_previous, unmatched_current, ambiguous = (
        comparison_detector.align_units(previous_units, current_units)
    )

    previous_index = _unit_index(record, "previous")
    current_index = _unit_index(record, "current")
    unit_keys = set(previous_index) | set(current_index)
    pointers = _evidence_pointers(result, unit_keys)
    detected_by_key = {
        key: (change_type, reason)
        for key, change_type, reason, _cid in _proposed_changes(result, unit_keys)
        if key is not None
    }

    alignments: list[dict[str, Any]] = []
    labels: list[dict[str, Any]] = []

    def _emit(
        *,
        previous_unit: dict[str, Any] | None,
        current_unit: dict[str, Any] | None,
        unit_key: str,
        alignment_basis: str,
    ) -> None:
        detected = detected_by_key.get(unit_key)
        if detected is not None:
            proposed_type, reason = detected
        elif previous_unit is not None and current_unit is not None:
            # Aligned and not emitted as a change: comparison.v1 has no
            # 'unchanged' change type, so absence IS the detector's claim of
            # unchanged. The packet states that explicitly instead of leaving
            # the reviewer to infer it from a missing row.
            proposed_type, reason = "unchanged", None
        else:
            proposed_type, reason = "undetermined", None

        previous_id = previous_unit["unit_id"] if previous_unit else None
        current_id = current_unit["unit_id"] if current_unit else None
        side = {
            "added": "current",
            "removed": "previous",
            "modified": "both",
            "unchanged": "both",
        }.get(proposed_type, "none")

        alignments.append(
            {
                "unit_key": unit_key,
                "alignment_basis": alignment_basis,
                "previous_unit_id": previous_id,
                "current_unit_id": current_id,
                "previous_heading": previous_unit["heading"] if previous_unit else None,
                "current_heading": current_unit["heading"] if current_unit else None,
                "previous_excerpt": previous_unit["excerpt"] if previous_unit else None,
                "current_excerpt": current_unit["excerpt"] if current_unit else None,
                "machine_proposed_change_type": proposed_type,
                "machine_proposed_undetermined_reason": reason,
                "evidence_chunk_ids": pointers.get(unit_key, {"previous": [], "current": []}),
                "proposal_source": rfb.ANNOTATION_MACHINE_PROPOSED,
            }
        )
        labels.append(
            {
                "label_id": rfb.label_id_for(pair_id, previous_id, current_id),
                "expected_change_type": proposed_type,
                "previous_unit_id": previous_id,
                "current_unit_id": current_id,
                "expected_reason_code": (
                    (reason or "").split(":", 1)[0].strip() or None
                    if proposed_type == "undetermined"
                    else None
                ),
                "expected_evidence_side": side,
                "expected_direction": None,
                "reviewer_note": None,
                "confidence": "low",
            }
        )

    for previous_unit, current_unit in pairs:
        _emit(
            previous_unit=previous_index.get(previous_unit.unit_key),
            current_unit=current_index.get(current_unit.unit_key),
            unit_key=previous_unit.unit_key,
            alignment_basis=(
                "exact_heading_match"
                if previous_unit.unit_key == current_unit.unit_key
                else "exact_content_match"
            ),
        )
    for unit in unmatched_previous:
        _emit(
            previous_unit=previous_index.get(unit.unit_key),
            current_unit=None,
            unit_key=unit.unit_key,
            alignment_basis="unmatched_previous",
        )
    for unit in unmatched_current:
        _emit(
            previous_unit=None,
            current_unit=current_index.get(unit.unit_key),
            unit_key=unit.unit_key,
            alignment_basis="unmatched_current",
        )
    for key in ambiguous:
        _emit(
            previous_unit=previous_index.get(key),
            current_unit=current_index.get(key),
            unit_key=key,
            alignment_basis="ambiguous_heading",
        )

    packet = {
        "schema_version": rfb.PACKET_SCHEMA_VERSION,
        "generated_by": PACKET_GENERATOR,
        "banner": MACHINE_PROPOSAL_BANNER,
        "benchmark_id": manifest["benchmark_id"],
        "pair_id": pair_id,
        "issuer_name": record["issuer_name"],
        "cik": record["cik"],
        "sector_label": record["sector_label"],
        "source_manifest_hash": record["source_manifest_hash"],
        "build_hash": record["build_hash"],
        "parser_versions": record["parser_versions"],
        "previous": _side_summary(record, "previous"),
        "current": _side_summary(record, "current"),
        "alignments": alignments,
        "detector_change_count": len(result.get("changes", [])) if result else 0,
        "excerpt_char_limit": rfb.MAX_EXCERPT_CHARS,
        "human_verification_required": True,
    }

    annotation = rfb.machine_proposed_annotation(
        pair_id=pair_id,
        source_manifest_hash=record["source_manifest_hash"],
        previous_section_hash=record["previous"]["section_hash"] or "",
        current_section_hash=record["current"]["section_hash"] or "",
        labels=labels,
        generated_by=PACKET_GENERATOR,
        benchmark_id=manifest["benchmark_id"],
    )
    rfb.validate_annotation_against_build(annotation, record)
    return packet, annotation


def _side_summary(record: dict[str, Any], side: str) -> dict[str, Any]:
    payload = record[side]
    return {
        "filing_id": payload["filing_id"],
        "extraction_outcome": payload["extraction_outcome"],
        "heading_detected": payload["heading_detected"],
        "section_hash": payload["section_hash"],
        "section_char_count": payload["section_char_count"],
        "unit_count": payload["unit_count"],
        "units": payload["units"],
    }


def render_markdown(packet: dict[str, Any]) -> str:
    """Human-readable local review form. Same content, easier to read."""
    lines = [
        f"# Annotation packet — {packet['pair_id']}",
        "",
        f"> **{packet['banner']}**",
        "",
        f"- Issuer: {packet['issuer_name']} (CIK {packet['cik']})",
        f"- Sector label (stratification only): {packet['sector_label']}",
        f"- Build hash: `{packet['build_hash']}`",
        f"- Manifest hash: `{packet['source_manifest_hash']}`",
        f"- Previous section hash: `{packet['previous']['section_hash']}`",
        f"- Current section hash: `{packet['current']['section_hash']}`",
        f"- Detector: `{packet['parser_versions']['detector']}`, "
        f"workflow `{packet['parser_versions']['workflow']}`",
        "",
        "## How to verify",
        "",
        "1. Read each row below and decide the change type yourself.",
        "2. Edit the machine-proposed annotation JSON next to this file.",
        "3. Correct `expected_change_type`, `expected_evidence_side`, and, where"
        " a directional claim is meaningful, `expected_direction`.",
        "4. Set `confidence` honestly. `low` is a legitimate answer.",
        "5. Only then set `annotation_status` to `human_verified` and fill in"
        " `annotator_id` and `verification_timestamp`.",
        "",
        "Leaving the file as generated keeps it machine-proposed, and a"
        " machine-proposed file contributes nothing to any metric.",
        "",
        f"## Aligned units ({len(packet['alignments'])})",
        "",
    ]
    for entry in packet["alignments"]:
        lines.extend(
            [
                f"### `{entry['unit_key']}` — {entry['alignment_basis']}",
                "",
                f"- machine-proposed change type: **{entry['machine_proposed_change_type']}**"
                " (proposal, not ground truth)",
                f"- previous unit: `{entry['previous_unit_id'] or '—'}`"
                f" {entry['previous_heading'] or ''}".rstrip(),
                f"- current unit: `{entry['current_unit_id'] or '—'}`"
                f" {entry['current_heading'] or ''}".rstrip(),
                f"- evidence chunks: previous="
                f"{len(entry['evidence_chunk_ids']['previous'])}, current="
                f"{len(entry['evidence_chunk_ids']['current'])}",
                "",
            ]
        )
        for side in ("previous", "current"):
            excerpt = entry[f"{side}_excerpt"]
            if excerpt:
                lines.extend(
                    [
                        f"<details><summary>{side} excerpt "
                        f"(≤{packet['excerpt_char_limit']} chars)</summary>",
                        "",
                        f"> {excerpt}",
                        "",
                        "</details>",
                        "",
                    ]
                )
    return "\n".join(lines) + "\n"


def validate_completed_annotation(
    path: str | Path, layout: rfb.CorpusLayout
) -> dict[str, Any]:
    """Import validator for a completed annotation file.

    Checks the schema, then binds it to the corpus build it claims to describe:
    section hashes must match and every referenced unit must exist. Returns a
    structured verdict; a caller decides the exit code.
    """
    annotation = rfb.load_annotation(path)
    record = builder.load_build_record(annotation["pair_id"], layout)
    rfb.validate_annotation_against_build(annotation, record)
    return {
        "pair_id": annotation["pair_id"],
        "annotation_status": annotation["annotation_status"],
        "is_gold": rfb.is_gold(annotation),
        "annotator_id_basis": (
            "self_asserted_local_metadata"
            if annotation["annotator_id"]
            else "none"
        ),
        "label_count": len(annotation["labels"]),
        "annotation_hash": rfb.annotation_hash(annotation),
        "build_hash": record["build_hash"],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate local machine-proposed annotation packets for human "
            "review, or validate a completed annotation file. Offline."
        )
    )
    parser.add_argument("--manifest", metavar="PATH", help="benchmark manifest path")
    parser.add_argument("--corpus-dir", metavar="PATH", help="local corpus directory")
    parser.add_argument(
        "--pair-id", action="append", default=[], help="only these pairs"
    )
    parser.add_argument(
        "--validate",
        metavar="PATH",
        help="validate a completed annotation file instead of generating packets",
    )
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    args = parser.parse_args(argv)

    layout = rfb.CorpusLayout(args.corpus_dir)

    if args.validate:
        try:
            verdict = validate_completed_annotation(args.validate, layout)
        except rfb.BenchmarkError as exc:
            print(f"Invalid annotation [{exc.code}]: {exc.message}", file=sys.stderr)
            return 1
        if args.json:
            print(json.dumps(verdict, indent=2, sort_keys=True))
        else:
            print(f"Annotation valid: {verdict['pair_id']}")
            print(f"  status      : {verdict['annotation_status']}")
            print(f"  labels      : {verdict['label_count']}")
            print(f"  counts as gold: {verdict['is_gold']}")
            if not verdict["is_gold"]:
                print(
                    "  This file does NOT contribute to any accuracy metric. "
                    "Only 'human_verified' does."
                )
        return 0

    try:
        manifest = rfb.load_manifest(args.manifest)
    except rfb.BenchmarkError as exc:
        print(f"Invalid benchmark manifest [{exc.code}]: {exc.message}", file=sys.stderr)
        return 2

    pair_ids = args.pair_id or [pair["pair_id"] for pair in rfb.manifest_pairs(manifest)]
    if not pair_ids:
        print(
            "The benchmark manifest has no resolved pairs, so there is nothing "
            "to review.",
            file=sys.stderr,
        )
        return 2

    written: list[dict[str, Any]] = []
    failures: list[dict[str, Any]] = []
    for pair_id in pair_ids:
        try:
            packet, annotation = build_packet(pair_id, layout, manifest)
        except rfb.BenchmarkError as exc:
            failures.append(
                {"pair_id": pair_id, "failure_code": exc.code, "detail": exc.message}
            )
            continue
        rfb.write_json_atomic(layout.packet_json_path(pair_id), packet)
        markdown_path = layout.packet_markdown_path(pair_id)
        markdown_path.parent.mkdir(parents=True, exist_ok=True)
        markdown_path.write_text(render_markdown(packet), encoding="utf-8")
        rfb.write_json_atomic(layout.machine_proposed_path(pair_id), annotation)
        written.append(
            {
                "pair_id": pair_id,
                "alignment_count": len(packet["alignments"]),
                "label_count": len(annotation["labels"]),
                "packet_path": layout.relative(layout.packet_json_path(pair_id)),
                "annotation_path": layout.relative(
                    layout.machine_proposed_path(pair_id)
                ),
                "annotation_status": annotation["annotation_status"],
            }
        )

    report = {
        "generated_by": PACKET_GENERATOR,
        "banner": MACHINE_PROPOSAL_BANNER,
        "packets_written": len(written),
        "packets_failed": len(failures),
        "packets": written,
        "failures": failures,
        "gold_labels_produced": 0,
    }
    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print(MACHINE_PROPOSAL_BANNER)
        print()
        for entry in written:
            print(
                f"  {entry['pair_id']:<28} alignments={entry['alignment_count']:<4} "
                f"labels={entry['label_count']:<4} status={entry['annotation_status']}"
            )
        for failure in failures:
            print(
                f"  FAIL {failure['pair_id']}: [{failure['failure_code']}] "
                f"{failure['detail']}"
            )
        print(
            f"\n{len(written)} packet(s) written to the local gitignored corpus "
            "directory. Zero verified labels were produced, because producing "
            "one requires a person."
        )
    return 0 if not failures else 1


if __name__ == "__main__":
    sys.exit(main())
